export PS1='\[\e]0;ROS2@Humble: \w\a\]\[\033[1;33m\]ROS2@Humble:\[\033[1;34m\]\w${debian_chroot:+($debian_chroot)}\[\033[00m\]\$ '
# export PS1='\[\e]0;\u@\h: \w\a\]\[\033[1;33m\]\u@\h:\[\033[1;34m\]\w${debian_chroot:+($debian_chroot)}\[\033[00m\]\$ '
